# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.DecimalField(decimal_places=5, max_digits=5)),
                ('word', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
